### ISSUE TITLE
Does not prevent ember-cli from copying other css to `assets`

### ISSUE THREAD

**Issue by ghost** [johnotander/ember-cli-rework#3]
Ember-cli treats all css besides `app.css` as an asset that should be copied to `dist/assets`. When using `rework-npm` to inline css that isn't what you'd expect. It would be better if this plugin could prevent ember from copying the css with an option set in the `Brocfile.js`.

Or should this be configured by the user outside of `ember-cli-rework`? I'm just asking for feedback, since this is one of several unexpected issues that I encountered with `ember-cli-rework` (another example is that it doesn't output any css for `production`, #1 ). Just trying to understand what's necessary to get it to work.

**Comment by ghost** [comment]
Ok, so this can be fixed with broccoli-funnel. Not sure if it should be, but it does the job. Example in https://github.com/ember-cli/ember-cli/issues/4009

**Comment by johno** [comment]
Thanks for digging in to this! I think that `ember-cli-rework` should be ensuring that CSS that isn't imported doesn't end up in the build. I've been rather stuck on the `production` problem in #1. I'm not quite sure what's going on there.
