### ISSUE TITLE
Unexpected behaviour with rework-suit

### ISSUE THREAD

**Issue by ghost** [johnotander/ember-cli-rework#4]
When using [rework-suit](https://github.com/suitcss/rework-suit)<sup>[1]</sup> with this addon several issues pop up. I've encountered these issues only when using rework-suit through ember-cli-rework, and not when using rework-suit directly in node:
- [rework-vars](https://github.com/reworkcss/rework-vars) does not recognise variables across files (but [rework-npm](https://github.com/reworkcss/rework-npm) concatenates all css  correctly, so this is counterintuitive)
- as you said in #1, `ember build --environment=production` results in an empty `app.css`
- when importing local css partials with rework-npm it uses `dist` as root, and isn't relative to `app/styles/app.css` (which is what you'd expect)
- css partials imported with rework-npm are copied to `dist/assets` (they can be excluded with broccoli-funnel, but maybe it would be more elegant if the exclusion could be done through this addon?)

I'd prefer to use this addon instead of broccoli-rework, so I'm wondering whether this addon is still under active development and whether there are any clues as to what's going wrong here ([is the addon using the correct hooks in the build process?](http://hashrocket.com/blog/posts/a-compendium-of-hooks-in-embercli)). I'd be happy to help fix them!

---

1: _rework-suit is a collection of rework plugins (rework-vars, rework-custom-media, rework-npm, rework-calc, rework-suit-conformance, rework-ie-limits)._

**Comment by johno** [comment]
I definitely haven't tried to use this addon with rework-suit. So, I'll have to take that for a spin to see what's going wrong there.

> so I'm wondering whether this addon is still under active development

Most definitely, : ).

> is the addon using the correct hooks in the build process?

I don't believe that it is currently being hooked correctly. When I initially wrote this addon I wasn't very savvy on the hooks. Currently I'm using the `postprocessTree` hook, however, I believe that it should be registering a preprocessor within  the app instead.

> I'd be happy to help fix them!

I'd gladly accept, and be grateful for, any PR/contribution. I'll be bogged down for the next day or two, so I won't be able to address these bugs, so if you want to go after them, be my guest. I suspect a good place to get started is basing it off the hooks that are used in a recent addon, [ember-cli-cssnext](https://github.com/ebryn/ember-cli-cssnext).

Thanks for reporting this!

**Comment by ghost** [comment]
Cool, no problem! I've made a quick sketch at https://github.com/ismay/ember-cli-rework/blob/refactor-to-preprocessor/ . I've changed the option object to `rework.plugins` to make room for global rework options (should we need to adress filtering css partials for example, but maybe ember-cli would take care of that now?).

I think the `reworkTree()` function at https://github.com/ismay/ember-cli-rework/blob/refactor-to-preprocessor/index.js#L19 still needs some work, mainly because I'm not exactly sure whether I'm implementing your logic correctly here. Couldn't find documentation on what's contained in a broccoli `tree` exactly, which makes integrating it with rework a little difficult :). Let me know if you have suggestions!

The rest looks fine for now, at first glance.

**Comment by ghost** [comment]
Oh btw., this 

> I think the reworkTree() function at https://github.com/ismay/ember-cli-rework/blob/refactor-to-preprocessor/index.js#L19 still needs some work

was because I was confusing the broccoli-rework with rework. No need to concern myself with what's in the `tree` with broccoli-rework :). So as far as I'm concerned this can be closed as it's all been fixed in #5 .
